### ISSUE TITLE
Few questions about the usage of the xps

### ISSUE THREAD

**Issue by coalwater** [konklone/debian#7]
This isn't an actual issue, but I am planning to buy a new laptop and I had the XPS in mind, I use debian jessie as my main OS so I wanted to get a little insight from your experience

 - The main usage of your laptop
What do you use your laptop mainly for? the answer is to mainly help answer the next question.

 - The screen size
I'm mainly a web developer, so I'm going to spend a long time writing code and switching back and forth between code and browser, do you think a 13' screen would be a pain for that purpose? should I go for 14' , 15' better?

 - Battery life
I currently have debian on a samsung laptop, the battery life isn't that good, does debian handle power management better on the XPS ? does it suffer ( a noticeable ) reduced performance on battery?

**Comment by konklone** [comment]
> What do you use your laptop mainly for?

I'm also a software (mostly web) developer. My work is maybe 50% writing code, 50% writing prose. I also use it to play games, whenever they work on Linux (e.g. some Steam games).

> I'm mainly a web developer, so I'm going to spend a long time writing code and switching back and forth between code and browser, do you think a 13' screen would be a pain for that purpose? should I go for 14' , 15' better?

I don't mind the 13" screen, but I also prefer a single screen to dual-monitor, which may make me unusual among developers. I find that I adapt pretty well to the screen in front of me.

> I currently have debian on a samsung laptop, the battery life isn't that good, does debian handle power management better on the XPS ? does it suffer ( a noticeable ) reduced performance on battery?

It's hard to compare, because I haven't used a Dell XPS with Windows. I know that my previous computer (a high-end Thinkpad) had notably worse battery power on Linux than on Windows. 

A good bit of that seemed to depend on using the high-end graphics card, though. The Dell XPS 13 that I have does not have a high-end graphics card. This is not great for my love of playing games, but it does mean that I can usually get 4-5 hours of battery life.

That said, 4-5 hours of battery life is not as great by today's standards as it once was. I do often have to "think about battery", and it's not as nice as what I think a lot of people get out of their Macbook Airs, for example.

Alllll of that said, you should know that Dell recently [refreshed their line of Linux computers](http://dell.com/ubuntu) to include an updated XPS 13, and the M3800. I don't have personal experience with either of those.

I'm closing the issue, but feel free to continue the conversation.

**Comment by coalwater** [comment]
First of all thanks for your reply, and thanks for the link, wasn't aware that the precision had an ubuntu version, will check that out.

What about the touch screen, the new gnome-shell trys to make use of touch screens and gestures, do you find that useful or do you just ignore the fact that you have a touch screen entirely ( which what I imagine i might end up doing )

**Comment by konklone** [comment]
> What about the touch screen, the new gnome-shell trys to make use of touch screens and gestures, do you find that useful or do you just ignore the fact that you have a touch screen entirely ( which what I imagine i might end up doing )

I love the touch screen in theory, and I show it to people when I'm showing off how much I love my computer -- but, in practice, I use it basically never during ordinary day-to-day life.

The capacitive touch screen is sensitive enough, but it is not as smooth or precise as a smartphone or tablet, or what I recall the Chromebook Pixel's screen to be. What the touch actually does (e.g. focus a button, or click a button) varies from app to app, and I find the implementation in Chrome and Firefox/Iceweasel to be frustratingly different.
